heat_template_version: rocky

parameters:
  flavor:
    type: string
    description: Flavor to use
    default: b.2c2gb
  image:
    type: string
    description: Image name
    default: Ubuntu 22.04 Jammy Jellyfish x86_64
  boot_volume_size:
    type: number
    description: Boot volume size
    default: 16
  key_name:
    type: string
    description: Keypair to inject into server
    default: ''
  public_net:
    type: string
    description: Public network name
    default: ext-net
  config_drive:
    type: boolean
    description: Use config_drive for metadata discovery
    default: true

resources:

  my_dockerhost:
    type: "OS::Nova::Server"
    properties:
      name: dockerhost
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: my_dockerhost_management_port }
      block_device_mapping_v2:
        - device_name: vda
          delete_on_termination: true
          image: { get_param: image }
          volume_size: { get_param: boot_volume_size }
      config_drive: { get_param: config_drive }
      user_data: { get_resource: my_config }
      user_data_format: RAW

  my_docker_volume:
    type: "OS::Cinder::Volume"
    properties:
      size: 5
      name: docker-volume

  my_docker_volume_attachment:
    type: "OS::Cinder::VolumeAttachment"
    properties:
      instance_uuid: { get_resource: my_dockerhost }
      volume_id: { get_resource: my_docker_volume }

  my_dockerhost_management_port:
    type: "OS::Neutron::Port"
    properties:
      network_id: { get_resource: my_net }
      security_groups:
        - { get_resource: my_security_group }

  my_net:
    type: "OS::Neutron::Net"
    properties:
      name: management-net

  my_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      name: management-sub-net
      network_id: { get_resource: my_net }
      cidr: 192.168.254.0/24
      gateway_ip: 192.168.254.254
      enable_dhcp: true
      dns_nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
      allocation_pools:
        - start: "192.168.254.200"
          end: "192.168.254.253"

  my_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Neutron security group rules
      name: my_security_group
      rules:
      - remote_ip_prefix: 0.0.0.0/0
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - remote_ip_prefix: 0.0.0.0/0
        protocol: icmp
        direction: ingress

  my_router:
    type: OS::Neutron::Router

  my_router_gateway:
    type: OS::Neutron::RouterGateway
    properties:
      router_id: { get_resource: my_router }
      network_id: { get_param: public_net }

  my_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: my_router }
      subnet_id: { get_resource: my_subnet }

  my_floating_ip:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network_id: { get_param: public_net }
      port_id: { get_resource: my_dockerhost_management_port }
    depends_on:
      - my_router_interface
      - my_router_gateway

  all_done_handle:
    type: OS::Heat::WaitConditionHandle

  all_done:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: all_done_handle}
      count: 1
      timeout: 600

  my_config:
    type: "OS::Heat::CloudConfig"
    properties:
      cloud_config:
        apt:
          sources:
            docker.list:
              source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
              keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        device_aliases:
          docker: '/dev/vdb'
        fs_setup:
          - filesystem: btrfs
            device: docker
        mounts:
          - [ 'docker', '/var/lib/docker' ]
        package_update: true
        package_upgrade: true
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        groups:
          - docker
        runcmd:
          - { get_attr: ['all_done_handle', 'curl_cli'] }
        system_info:
          default_user:
            groups: [docker]

outputs:
  public_ip:
    description: Floating IP address in public network
    value: { get_attr: [ my_floating_ip, floating_ip_address ] }
